name: Trigger auto deployment for game-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/game-service-AutoDeployTrigger-b48d2d6a-85de-461a-9ade-386e130b2b2b.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.GAMESERVICE_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GAMESERVICE_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GAMESERVICE_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: hub.docker.com
          registryUsername: ${{ secrets.GAMESERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GAMESERVICE_REGISTRY_PASSWORD }}
          containerAppName: game-service
          resourceGroup: dodo-workshop
          imageToBuild: hub.docker.com/game-service:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


